#!/usr/bin/env bash
#0. World wide web

print_subd ()
{
	printf "The subdomain %s is a " "$2"
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $4}'
	printf " record and points to "
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $5}'
	echo ""
}

if [ -z $2 ]
then
	for subsdomains in "www" "lb-01" "web-01" "web-02"
	do
		print_subd "$1" "$subsdomains"
	done
else
	print_subd "$1" "$2"
fi
