#!/usr/bin/env bash
#0. World wide web

print_subd ()
{
    printf "is a " ; dig "$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]
then
printf "The subdomain www "
print_subd "www.$1"

printf "The subdomain lb-01"
print_subd "lb-01.$1"

printf "The subdomain web-01 "
print_subd "web-01.$1"

printf "The subdomain web-02 "
print_subd "web-02.$1"

else
    printf "The subdomain %s " "$2"
    print_subd "$2.$1"
fi
