#!/usr/bin/env bash
#Task 3

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/page404.html
sed -i '/server_name _;/a  error_page 404 /page404.html;' /etc/nginx/sites-available/default
service nginx restart

