#!/usr/bin/env bash
#display bad luck in 4th, good luck 8th, best school the rest x10

i=1
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
