#!/usr/bin/env bash
#script that displays numbers from 1 to 20
#Disply bad luck frm china 4th, bad luck frm japan 9th, bad luck frm italy 17th

i=1
while [ "$i" -le 20 ]
do
	echo "$i"
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	(( i++ ))
done
