#!/usr/bin/env bash
#script that gives you information about the school file

file="School"

if [ -e "$file" ]; then
	echo "$file school file exists"
	if [ -s "$file" ]; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f "$file" ]; then
		echo "$file file is a regular"
	fi
else
	echo "$file file does not exist"
fi
