#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01.

sudo apt update -y
sudo apt install ufw -y
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw disable && sudo ufw enable

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

sudo ufw enable
